name: Sync with Trello

on:
  issues: 
    types: ['opened']

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Link GitHub Issue and Pull Request with Trello Card
          uses: jessicazu/trello-github-actions@v1.0
          env:
            TRELLO_API_KEY: "c4a14a5f19e29bcb97d3489a8a4f9e48"
            TRELLO_API_TOKEN: "095a63d05790da2bcaa5f6384499d9eccce5b372111fe251aad56df39de06a6d"
            TRELLO_BOARD_ID: "5e77376916063b42f14e0ef1"
            TRELLO_LIST_ID: "5ea87729b91a9e61b5b08ea3"
